services:
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb

  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=my_db
      - MARIADB_USER=db
      - MARIADB_PASSWORD=db
      - TZ=America/Sao_Paulo
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb my_db -udb -pdb -e 'SELECT 1;'  || exit 1"]
      interval: 2s
      retries: 10

  app:
    image: app:latest
    build: .
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mariadb+pymysql://db:db@mariadb/my_db?charset=utf8mb4
    ports:
      - 9000:5000
